allowBuilds:
  core-js-pure: true
  dtrace-provider: true
  protobufjs: false
  re2: true
minimumReleaseAge: 4320 # Keep this in sync with Renovate `security:minimumReleaseAgeNpm`.
minimumReleaseAgeStrict: false
pmOnFail: download
