name: Changesets auto-merge
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
permissions: {}
concurrency:
  group: ${{ github.workflow }}
jobs:
  changesets:
    name: "Changesets: Merge"
    runs-on: ubuntu-24.04
    steps:
      - name: Merge the Changesets Release pull request
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GH_REPO: ${{ github.repository }}
        run: |
          pull_request_number="$(
            gh pr list --base main --head changeset-release/main --state open --json number --jq '.[0].number // empty'
          )"

          if [[ -n "${pull_request_number}" ]]; then
            gh pr merge "${pull_request_number}" --squash
          else
            echo "No open Release pull request to merge."
          fi
