name: Renovate
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      is-dry-run:
        description: Whether this is a dry run. If true, Renovate will resolve updates without opening pull requests.
        type: boolean
        default: false
      log-level:
        description: The log level to use for Renovate.
        type: choice
        default: info
        options:
          - trace
          - debug
          - info
          - warn
          - error
          - fatal
concurrency:
  cancel-in-progress: true
  group: renovate
permissions:
  contents: read
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install PNPM
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: pnpm
          node-version-file: .node-version
      - name: Install Node.js dependencies
        run: pnpm install
      - id: release-bot-token
        name: Mint psirenny Bot installation token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.RELEASE_BOT_APP_CLIENT_ID }}
          private-key: ${{ secrets.RELEASE_BOT_APP_PRIVATE_KEY }}
      - name: Run Renovate
        env:
          LOG_FILE: ${{ runner.temp }}/renovate.log
          LOG_FILE_LEVEL: warn
          LOG_LEVEL: ${{ inputs.log-level }}
          RENOVATE_ALLOWED_COMMANDS:
            '["^pnpm install --frozen-lockfile --ignore-scripts$", "^pnpm run build$", "^node dist/cli\\.js$", "^pnpm
            run oxfmt:fix$"]'
          RENOVATE_BINARY_SOURCE: global
          RENOVATE_DRY_RUN: ${{ inputs.is-dry-run == true && 'full' || '' }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_TOKEN: ${{ steps.release-bot-token.outputs.token }}
        run: pnpm exec renovate
      - name: Assert Renovate reported no warnings or errors
        if: ${{ !cancelled() }}
        env:
          log_file_path: ${{ runner.temp }}/renovate.log
        run: |
          if [[ -s "${log_file_path}" ]]; then
            cat "${log_file_path}"
            exit 1
          fi
